name: Deploy Flutter Web in Docker Container to Ubuntu Server
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.CONTAINERIO_USER }}
        password: ${{ secrets.CONTAINERIO_PASSWORD }}
        registry: cloud.canister.io:5000
        
        
#     - name: Build Docker image
#       run: docker build . --file Dockerfile

#     - name: Docker Tag
#       run: docker tag latest cloud.canister.io:5000/pacebrian0/conciergeweb:latest
          
#     - name: Docker Push
#       run: docker push cloud.canister.io:5000/pacebrian0/conciergeweb

#     - name: Build and push
#       uses: docker/build-push-action@v3
#       with:
#         file: Dockerfile
#         push: true
#         provenance: false
#         tags: cloud.canister.io:5000/pacebrian0/conciergeweb:latest

    - name: Build and push
      uses: opspresso/action-docker@master
      # with:
      env:
        USERNAME: ${{ secrets.CONTAINERIO_USER }}
        PASSWORD: ${{ secrets.CONTAINERIO_PASSWORD }}
        REGISTRY: cloud.canister.io:5000
        IMAGE_NAME: ${{ secrets.CONTAINERIO_USER }}/conciergeweb
        DOCKERFILE: Dockerfile
        LATEST: "true" 
        
#     - name: Push Docker image to Docker Hub
#       uses: docker/build-push-action@v4
#       with:
#         push: true
#         tags: pacebrian0/conciergeweb:latest

    - name: Deploy Docker container to Ubuntu Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          docker login --username=${{ secrets.CONTAINERIO_USER }} --password=${{ secrets.CONTAINERIO_PASSWORD }} cloud.canister.io:5000
          
          docker pull cloud.canister.io:5000/pacebrian0/conciergeweb:latest
          docker image list
          docker stop  pacebrian0/conciergeweb || true
          docker rm p pacebrian0/conciergeweb|| true
          docker run -d --name conciergeweb -p 80:80  pacebrian0/conciergeweb:latest
