name: Deploy Flutter Web in Docker Container to Ubuntu Server
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.CONTAINERIO_USER }}
        password: ${{ secrets.CONTAINERIO_PASSWORD }}
        registry: cloud.canister.io:5000
        
        
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag latest

    - name: Docker Tag
      run: docker tag latest pacebrian0/conciergeweb
          
    - name: Docker Push
      run: docker push pacebrian0/conciergeweb
      
#     - name: Push Docker image to Docker Hub
#       uses: docker/build-push-action@v4
#       with:
#         push: true
#         tags: pacebrian0/conciergeweb:latest

    - name: Deploy Docker container to Ubuntu Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_SSH_PORT }}
        script: |
          docker pull container.io/pacebrian0/conciergeweb:latest
          docker stop  container.io/pacebrian0/conciergeweb || true
          docker rm p container.io/pacebrian0/conciergeweb|| true
          docker run -d --name conciergeweb -p 80:80  container.io/pacebrian0/conciergeweb:latest
